languaje: node_js
cache:
  directories
    - node_modules
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
script:
  - yarn build
notifications:
  slack: laboratorioplatzi:hLwWi7KlucuNBjy7w11a8BmV
  email:
    recipients:
      - mariocastro.pva@gmail.com
      - mariocastro.dev@gmail.com
    on_success: always
    on_failure: always
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: gh-pages
  commit-message: "Deploy del Proyecto"
  on:
    branch: master

